apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: test-job-main
      imagePullPolicy: Always
      imageRegistry: test url/hello
      imagePullSecretName: imagepull-docker
      credentialId: credential_65e364fc-42c6-4fa4-9fc9-3b1bfb80218f
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: test-job
    version: v1.0.0
    applicationId: app_55d03112-24c7-4d7d-96c6-6f8cd80d39cd
    projectId: project_8f8d485e-68f3-4bb6-9c53-3bfb0aea8806
    organizationId: org_fc18b32c-00a4-49d7-94ab-ee96b2c9569d
    environmentId: env_496b65c5-be22-405d-9b17-81901f3b476a
    environmentName: prod
  horizontalAutoScalingRules: []
  volumes: []
  type: CronJob
  name: test job
  cronTab: 30 2 * * 5
  serviceType: ClusterIP
  version: v1.0.0
  namespace: test-project-thameera-prod
