apiVersion: v1
kind: Namespace
metadata:
  name: testthameera3-staging
  labels:
    environment-id: env_498068ae-fee0-4817-bde3-788e3a339977
    project-id: project_ab141b56-a92f-4f7e-8619-21975add4a0e
    project-name: testThameera3
    environment-name: staging
    organization-id: org_868a1fb2-9728-4c44-b9b4-88742ac7fd14
