apiVersion: v1
kind: Namespace
metadata:
  name: test-project-thameera-prod
  labels:
    environment-id: env_496b65c5-be22-405d-9b17-81901f3b476a
    project-id: project_8f8d485e-68f3-4bb6-9c53-3bfb0aea8806
    project-name: test project thameera
    environment-name: prod
    organization-id: org_fc18b32c-00a4-49d7-94ab-ee96b2c9569d
