apiVersion: v1
kind: Namespace
metadata:
  name: testprothameera-dev
  labels:
    environment-id: env_4966c033-aa86-47a4-bb2a-2215848efd40
    project-id: project_bdbc1817-8f27-46c9-9619-1037f88ba00c
    project-name: testProThameera
    environment-name: dev
    organization-id: org_1228d3e1-6b7e-4820-97f5-d9bc2cc5e4cf
